### ISSUE TITLE
appleseed crashes when trying to do a progressive render using SPPM

### ISSUE THREAD

**Issue by est77** [appleseedhq/appleseed#2036]
Using SPPM with the progressive render is not supported. We should report and error and abort the render without crashing.

```
#0  0x00007f7a8d9869ab in renderer::(anonymous namespace)::SPPMLightingEngine::PathVisitor::add_photon_map_lighting_contribution(renderer::PathVertex const&, renderer::DirectShadingComponents&) ()
   from /opt/gaffer-0.45.0.0-linux/appleseed/lib/libappleseed.so
#1  0x00007f7a8d98b467 in renderer::(anonymous namespace)::SPPMLightingEngine::compute_lighting(foundation::QMCSamplingContext<foundation::Xoroshiro128plus>&, renderer::PixelContext const&, renderer::ShadingContext const&, renderer::ShadingPoint const&, renderer::ShadingComponents&) [clone .part.100] () from /opt/gaffer-0.45.0.0-linux/appleseed/lib/libappleseed.so
#2  0x00007f7a8d98e525 in renderer::(anonymous namespace)::SPPMLightingEngine::compute_lighting(foundation::QMCSamplingContext<foundation::Xoroshiro128plus>&, renderer::PixelContext const&, renderer::ShadingContext const&, renderer::ShadingPoint const&, renderer::ShadingComponents&) () from /opt/gaffer-0.45.0.0-linux/appleseed/lib/libappleseed.so
#3  0x00007f7a8dc3fe68 in renderer::(anonymous namespace)::PhysicalSurfaceShader::evaluate(foundation::QMCSamplingContext<foundation::Xoroshiro128plus>&, renderer::PixelContext const&, renderer::ShadingContext const&, renderer::ShadingPoint const&, renderer::AOVAccumulatorContainer&, renderer::ShadingResult&) const () from /opt/gaffer-0.45.0.0-linux/appleseed/lib/libappleseed.so
#4  0x00007f7a8da0d444 in renderer::ShadingEngine::shade_hit_point(foundation::QMCSamplingContext<foundation::Xoroshiro128plus>&, renderer::PixelContext const&, renderer::ShadingContext const&, renderer::ShadingPoint const&, renderer::AOVAccumulatorContainer&, renderer::ShadingResult&) const () from /opt/gaffer-0.45.0.0-linux/appleseed/lib/libappleseed.so
#5  0x00007f7a8d9cc05e in renderer::(anonymous namespace)::GenericSampleRenderer::render_sample(foundation::QMCSamplingContext<foundation::Xoroshiro128plus>&, renderer::PixelContext const&, foundation::Vector<double, 2ul> const&, renderer::AOVAccumulatorContainer&, renderer::ShadingResult&) () from /opt/gaffer-0.45.0.0-linux/appleseed/lib/libappleseed.so
#6  0x00007f7a8d9cb55d in renderer::(anonymous namespace)::GenericSampleGenerator::generate_samples(unsigned long, std::vector<renderer::Sample, std::allocator<renderer::Sample> >&) ()
   from /opt/gaffer-0.45.0.0-linux/appleseed/lib/libappleseed.so
#7  0x00007f7a8d9f1d6d in renderer::SampleGeneratorBase::generate_samples(unsigned long, renderer::SampleAccumulationBuffer&, foundation::IAbortSwitch&) () from /opt/gaffer-0.45.0.0-linux/appleseed/lib/libappleseed.so
#8  0x00007f7a8d9db12a in renderer::SampleGeneratorJob::execute(unsigned long) () from /opt/gaffer-0.45.0.0-linux/appleseed/lib/libappleseed.so
#9  0x00007f7a8d8d86f6 in foundation::WorkerThread::execute_job(foundation::IJob&) () from /opt/gaffer-0.45.0.0-linux/appleseed/lib/libappleseed.so
#10 0x00007f7a8d8d9905 in foundation::WorkerThread::run() () from /opt/gaffer-0.45.0.0-linux/appleseed/lib/libappleseed.so
#11 0x00007f7ab1fe5556 in thread_proxy () from /opt/gaffer-0.45.0.0-linux/lib/libboost_thread.so.1.61.0
#12 0x00007f7abdb90df5 in start_thread () from /lib64/libpthread.so.0
#13 0x00007f7abd1b51ad in clone () from /lib64/libc.so.6
```

**Comment by est77** [comment]
It comes from Gaffer. I should report an error and abort in Gafferseed, 
but it we get to appleseed, we shouldn't crash.

**Comment by dictoon** [comment]
I agree.
